### ISSUE TITLE
is this library working?

### ISSUE THREAD

**Issue by mgarciadelojo** [acarmisc/pylemonway#1]
Hi @acarmisc,

First of all, thank you for your time, I see this library as a good starting point to implement Lemonway in python :D Unfortunately, I see this error when trying to use it...

```
  File "/Users/mgarciadelojo/.virtualenvs/petycash/lib/python3.5/site-packages/pylemonway/pylemonway.py", line 5, in <module>
    from lexceptions import LemonwayException
ImportError: No module named 'lexceptions'
```

I think you should use this import statement:

```
    from .lexceptions import LemonwayException
```

Thanks in advance,

**Comment by acarmisc** [comment]
Hi. I've to update the repo... I've continued working locally, I think I'll do it by the end of tomorrow. Sorry.

**Comment by mgarciadelojo** [comment]
No worries! I really appreciate your work and I'd glad to help, tell me if you need to add functionalities or whatever so I can create a pull request ;)

**Comment by mgarciadelojo** [comment]
Thank you for accepting my pull request. Let me now if you need some help.
